return {
	lspKind = {
		Text = "󰊄",
		Method = "m",
		Function = "󰊕",
		Constructor = "",
		Field = "",
		Variable = "󰫧",
		Class = "",
		Interface = "",
		Module = "",
		Property = "",
		Unit = "",
		Value = "",
		Enum = "",
		Keyword = "󰌆",
		Snippet = "",
		Color = "",
		File = "",
		Reference = "",
		Folder = "",
		EnumMember = "",
		Constant = " ",
		Struct = "",
		Event = "",
		Operator = "",
		Associated = "",
		TypeParameter = " ",

		Number = " ",
		String = " ",
		Boolean = " ",
		Array = " ",
		Object = " ",
	},

	git = {
		Add = "",
		Mod = "",
		Remove = "",
		Ignore = "",
		Rename = "",
		Diff = "",
		Repo = "",
		Octoface = "",
	},

	diagnostics = {
		Error = "",
		Warn = "",
		Info = "",
		Hint = "",
		Other = "",
	},

	misc = {
		Robot = "ﮧ",
		Squirrel = "",
		Tag = "",
		Watch = "",
		-- for backup
		package_pending = " ",
		package_installed = " ",
		package_uninstalled = " ﮊ",
		fake = "◉",
		seperator = "",

		-- for telescope
		Telescope = "",
		Lock = " ",
		Circle = " ",
		BigCircle = " ",
		BigUnfilledCircle = " ",
		Close = " ",
		NewFile = "",
		Search = "",
		Lightbulb = "",
		Project = "",
		Dashboard = "",
		History = "",
		Comment = "",
		Bug = "",
		Code = "",
		Gear = "",
		Package = "",
		List = "",
		SignIn = "",
		Check = "",
		Fire = "",
		Note = "",
		BookMark = "",
		Pencil = "",
		ChevronRight = ">",
		Table = "",
		Calendar = "",

		File = " ",
		Files = " ",
		Folder = " ",
		OpenFolder = " ",

		quit = "",
	},
	os = {
		linux = " ",
		macos = " ",
		windows = " ",
	},
	extensions = {
		commit = "",
		css = "",
		edit = "",
		fugitive = "",
		go = "",
		html = "",
		help = "",
		java = "",
		javascript = "",
		jproperties = "",
		json = "",
		jsp = "",
		lua = "",
		markdown = "",
		merge = "",
		sh = "",
		sql = "",
		text = "",
		vim = "",
		xml = "",
		zsh = "",
	},
	vscode_like = {
		File = " ",
		Module = " ",
		Namespace = " ",
		Package = " ",
		Class = " ",
		Method = " ",
		Property = " ",
		Field = " ",
		Constructor = " ",
		Enum = " ",
		Interface = " ",
		Function = " ",
		Variable = " ",
		Constant = " ",
		String = " ",
		Number = " ",
		Boolean = " ",
		Array = " ",
		Object = " ",
		Key = " ",
		Null = " ",
		EnumMember = " ",
		Struct = " ",
		Event = " ",
		Operator = " ",
		TypeParameter = " ",
	},

	borderchars = {
		"─",
		"│",
		"─",
		"│",
		"╭",
		"╮",
		"╯",
		"╰",
	},

	dashboard = {
		find = "󰈞",
		file = "",
		project = "",
		recent = "",
		text = "󰊄",
		config = "",

		quit = "",
		date = "",
		time = "",
	},
}
