return {
    lspKind = {
        Text = "󰊄",
        Method = "m",
        Function = "󰊕",
        Constructor = "",
        Field = "",
        Variable = "󰫧",
        Class = "",
        Interface = "",
        Module = "",
        Property = "",
        Unit = "",
        Value = "",
        Enum = "",
        Keyword = "󰌆",
        Snippet = "",
        Color = "",
        File = "",
        Reference = "",
        Folder = "",
        EnumMember = "",
        Constant = " ",
        Struct = "",
        Event = "",
        Operator = "",
        Associated = "",
        TypeParameter = " ",

        Number = " ",
        String = " ",
        Boolean = " ",
        Array = " ",
        Object = " ",
    },

    git = {
        Add = "",
        Mod = "",
        Remove = "",
        Ignore = "",
        Rename = "",
        Diff = "",
        Repo = "",
        Octoface = "",
    },

    diagnostics = {
        Error = "",
        Warn = "",
        Info = "",
        Hint = "",
        Other = "",
    },

    misc = {
        Robot = "ﮧ",
        Squirrel = "",
        Tag = "",
        Watch = "",
        -- for backup
        package_pending = " ",
        package_installed = " ",
        package_uninstalled = " ﮊ",
        fake = "◉",
        seperator = "",

        -- for telescope
        Telescope = "",
        Lock = " ",
        Circle = " ",
        BigCircle = " ",
        BigUnfilledCircle = " ",
        Close = " ",
        NewFile = "",
        Search = "",
        Lightbulb = "",
        Project = "",
        Dashboard = "",
        History = "",
        Comment = "",
        Bug = "",
        Code = "",
        Gear = "",
        Package = "",
        List = "",
        SignIn = "",
        Check = "",
        Fire = "",
        Note = "",
        BookMark = "",
        Pencil = "",
        ChevronRight = ">",
        Table = "",
        Calendar = "",

        File = " ",
        Files = " ",
        Folder = " ",
        OpenFolder = " ",

        quit = "",
    },
    os = {
        linux = " ",
        macos = " ",
        windows = " ",
    },
    extensions = {
        commit = "",
        css = "",
        edit = "",
        fugitive = "",
        go = "",
        html = "",
        help = "",
        java = "",
        javascript = "",
        jproperties = "",
        json = "",
        jsp = "",
        lua = "",
        markdown = "",
        merge = "",
        sh = "",
        sql = "",
        text = "",
        vim = "",
        xml = "",
        zsh = "",
    },
    vscode_like = {
        File = " ",
        Module = " ",
        Namespace = " ",
        Package = " ",
        Class = " ",
        Method = " ",
        Property = " ",
        Field = " ",
        Constructor = " ",
        Enum = " ",
        Interface = " ",
        Function = " ",
        Variable = " ",
        Constant = " ",
        String = " ",
        Number = " ",
        Boolean = " ",
        Array = " ",
        Object = " ",
        Key = " ",
        Null = " ",
        EnumMember = " ",
        Struct = " ",
        Event = " ",
        Operator = " ",
        TypeParameter = " ",
    },

    borderchars = {
        "─",
        "│",
        "─",
        "│",
        "╭",
        "╮",
        "╯",
        "╰",
    },

    dashboard = {
        find = "󰈞",
        file = "",
        project = "",
        recent = "",
        text = "󰊄",
        config = "",

        quit = "",
        date = "",
        time = "",
    },


    go = {
        -- 用到的
        Interface = "ⓘ",
        Function = "ⓕ", -- 󰊕
        Field = "ⓕ",
        Method = "ⓜ",
        Variable = "ⓥ",
        Constant = "ⓒ",
        Type = "Ⓣ",
        Struct = "Ⓣ",
        Class = "Ⓣ",
        Text = "󰉿", -- 主要是buffer和dictionary来源
        Keyword = "", -- lsp来源的go关键词，直接不用icon，类似golang
        Module = "ⓟ", -- 包名，用于方便导入第3方包
        Snippet = "",
        TypeParameter = "󰊄",
        Treesitter = "", -- treesiter 补全的，不知道啥时候会用到，也不知道用啥icon，先放个空吧
        TabNine = "",

        -- 应该没用到的
        Constructor = "󰏿",
        Namespace = "󰌗",
        Unit = "󰑭",
        Value = "󰎠",
        Enum = "",
        Color = "󰏘",
        File = "󰈚",
        Property = "󰜢",
        Reference = "󰈇",
        Folder = "󰉋",
        EnumMember = "",
        Event = "",
        Operator = "󰆕",
        Table = "",
        Object = "󰅩",
        Tag = "",
        Array = "[]",
        Boolean = "",
        Signature = "",
        Number = "",
        Null = "󰟢",
        Supermaven = "",
        String = "󰉿",
        Calendar = "",
        Watch = "󰥔",
        Package = "",
        Copilot = "",
        Codeium = "",
        Ripgrep = "",
        Dictionary = "󰉋",
    }
}
